config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'schedule/sync'
  end

  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end

  scope :manage do
    resources :admins
    resources :tellers
    resources :events
    resources :locations
    resources :schedules
    resources :vendors
  end

  root 'admins#index'
end

app/views/admins/_form.html.erb
<%= form_for(@admin, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h4>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admins/edit.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @admin, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing admin</h1>
</div>

<%= render 'form' %>

app/views/admins/index.html.erb
<div class="page-header">
<%= link_to new_admin_path, :class => 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Admin
<% end %>
<h1>Listing Admins</h1>
</div>

<div class="row">
  <div class="table-responsive admins-index col-xs-12">
    <table class="table table-striped table-bordered table-hover dataTable" data-datatable-not-orderable="-3,-2,-1">
      <thead>
        <tr>
          <th>Email</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @admins) do |admin| %>
          <td><%= admin.email %></td>
          <td><%= link_to 'Show', admin %></td>
          <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
          <td><%= link_to 'Delete', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/new.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Admin</h1>
</div>

<%= render 'form' %>

app/views/admins/show.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_admin_path(@admin), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show admin</h1>
</div>

<dl class="dl-horizontal">
  <dt>Email:</dt>
  <dd><%= @admin.email %></dd>

  <dt>Last Sign In:</dt>
  <dd><%= @admin.last_sign_in_at %></dd>

  <dt>Last Updated:</dt>
  <dd><%= @admin.updated_at %></dd>
</dl>