config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'schedule/sync'
  end

  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end

  scope :manage do
    resources :admins
    resources :tellers
    resources :events
    resources :locations
    resources :schedules
    resources :vendors
  end

  root 'admins#index'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  mount_uploader :map, MapUploader
  
  attr_accessor :user_input_start, :user_input_end
  before_validation :process_user_input_dates

  validates :title, :start, :end_at, presence: true
  validates :start, timeliness: { type: :date }
  validates :end_at, timeliness: { after: :start, type: :date, after_message: "must be after start date." }

  # Note: The tellers method currently relies on this one to correctly
  # retrieve the tellers for the schedule. If this method is changed
  # in some strange way, the tellers method may need to be updated.
  # This also applies to the locations method.
  def events
    # We chose to connect Events with schedules dynamically in an effort to save the user effort.
    # We thought they may want to reuse events and/or enter them before creating the schedule they belong
    # to. The idea was that using the dates and times that they needed to enter anyway would save them from
    # having to go back and forth to think about which schedule an event belongs in and to move them around.
    # It ultimately works, but it may have been better to stick with a has_many relationship and either
    # make the user explicitly choose a schedule, or to come up with a different UI for managing them.
    #
    # There has to be a better way than this ugly hack to compare the dates with
    # datetimes correctly.
    Event.where("start >= ? AND end_at <= ?", start.beginning_of_day.to_datetime.change(offset: "+0000"), self[:end_at].end_of_day.to_datetime.change(offset: "+0000")).includes(:tellers)
  end

  def tellers
    # The call below works regardless of how the events method is defined.
    # Teller.joins(:events).where("start >= ? AND end <= ?", start, self[:end])

    # Using the events method, we reduce duplication, but may also introduce a problem
    # if that method requires something unique.
    # Theoretically, the tellers should always be pulled from the events which should
    # be defined correctly in that method.
    Teller.joins(:events).merge(events).unscope(:includes).distinct
  end

  def locations
    # This depends on the events method being defined sanely.
    Location.joins(:events).merge(events).unscope(:includes).distinct
  end

  private

  # Process dates entered by the user on the Schedule form.
  # This is used to allow the user to enter US-formatted dates
  # (m/d/y) instead of Ruby's default of the more common international
  # format (d/m/y).
  # There may be a better way to do this, but I couldn't find one at
  # the time.
  def process_user_input_dates
    [ [user_input_start, :start], [user_input_end, :end_at] ].each do |input, attribute|
      unless input.blank?
        self[attribute] = Date.strptime(input, "%m/%d/%Y")
      end
    end
  end
end

app/controllers/api/schedule_controller.rb
class Api::ScheduleController < ApplicationController
  def sync
    # Change this value to change the length of time that results are cached.
    @cache_time = 10.minutes

    @schedule = Rails.cache.fetch("api-schedule", expires_in: @cache_time, race_condition_ttl: 5.seconds) do
      Schedule.order("end_at DESC").first
    end

    if @schedule.blank?# && @schedule.updated_at > sync_date
      # We should do something more useful if no schedule is returned.
      render nothing: true
      return
    end

    @vendors = Vendor.active

    respond_to do |format|
      format.html { render html: 'Invalid use of API' }
      format.json { render }
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @events = @schedule.events
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:title, :start, :end_at, :map, :map_cache, :user_input_start, :user_input_end)
    end
end

app/helpers/api/schedule_helper.rb
module Api::ScheduleHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule, :multipart => true, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @schedule.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h4>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user_input_start, :class => "form-control dtp-date-only", autocomplete: "off", value: (@schedule.start.to_s(:moment_date_format) if @schedule.start) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_at, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user_input_end, :class => "form-control dtp-date-only", autocomplete: "off", value: (@schedule.end_at.to_s(:moment_date_format) if @schedule.end_at) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :map, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= image_tag(@schedule.map.thumb.url) if @schedule.map? %>
      <%= f.file_field :map, :class => "form-control" %>
      <%= f.hidden_field :map_cache %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @schedule, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Schedule</h1>
</div>

<%= render 'form' %>

app/views/schedules/index.html.erb
<div class="page-header">
<%= link_to new_schedule_path, :class => 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Schedule
<% end %>
<h1>Listing Schedules</h1>
</div>

<div class="row">
  <div class="table-responsive schedules-index col-xs-12">
    <table class="table table-striped table-bordered table-hover dataTable" data-datatable-order="1" data-datatable-not-orderable="3,-3,-2,-1">
      <thead>
        <tr>
          <th>Title</th>
          <th>Start</th>
          <th>End</th>
          <th class="text-right">Has Map?</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @schedules) do |schedule| %>
          <td><%= schedule.title %></td>
          <td><%= schedule.start %></td>
          <td><%= schedule.end_at %></td>
          <td class="text-right"><%= schedule.map? ? "✓" : "✗" %></td>
          <td><%= link_to 'Show', schedule %></td>
          <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
          <td><%= link_to 'Delete', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New schedule</h1>
</div>

<%= render 'form' %>

app/views/schedules/show.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_schedule_path(@schedule), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Schedule</h1>
</div>

<div class="row">
  <div class="col-md-9">
    <dl class="dl-horizontal">
      <dt>Title:</dt>
      <dd><%= @schedule.title %></dd>

      <dt>Start:</dt>
      <dd><%= @schedule.start.to_s(:moment_date_format) %></dd>

      <dt>End:</dt>
      <dd><%= @schedule.end_at.to_s(:moment_date_format) %></dd>
    </dl>
  </div>
  <div class="col-md-3">
    <div class="visible-lg pull-right">
      <%= link_to image_tag(@schedule.map.thumb.url, class: "img-responsive"), @schedule.map.url %>
    </div>

    <div class="hidden-lg">
      <%= link_to image_tag(@schedule.map.thumb.url, class: "img-responsive"), @schedule.map.url %>
    </div>
  </div>
</div>

<div class="row">
  <h2>Schedule of Events</h2>
</div>
<%= render 'partials/events_table' %>