config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'schedule/sync'
  end

  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end

  scope :manage do
    resources :admins
    resources :tellers
    resources :events
    resources :locations
    resources :schedules
    resources :vendors
  end

  root 'admins#index'
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	STATUS = ["active", "inactive"]
  validates :name,:location, presence: true, length: {:maximum => 100}


  validates :status, :inclusion => { :in => STATUS,
    :message => "%{value} is not a valid status" }

  scope :active, lambda{where(:status=>'active')}
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :location, :foods_list, :status)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @vendor.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h4>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :foods_list, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :foods_list, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :status, Vendor::STATUS, {}, { :class => "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @vendor, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Vendor</h1>
</div>

<%= render 'form' %>

app/views/vendors/index.html.erb
<div class="page-header">
  <%= link_to new_vendor_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Vendor
  <% end %>
  <h1>Listing Vendors</h1>
</div>

<div class="row">
  <div class="table-responsive vendors-index col-xs-12">
    <table class="table table-striped table-bordered table-hover dataTable" data-datatable-not-orderable="-4,-3,-2,-1">
      <thead>
        <tr>
          <th>Name</th> 
          <th>Location</th> 
          <th>Foods list</th>
          <th>Status</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @vendors) do |vendor| %>
          <td><%= vendor.name %></td> 
          <td><%= vendor.location %></td> 
          <td><%= vendor.foods_list %></td> 
          <td><%= vendor.status %></td> 
          <td><%= link_to 'Show', vendor %></td>
          <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
          <td><%= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/vendors/new.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Vendor</h1>
</div>

<%= render 'form' %>

app/views/vendors/show.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_vendor_path(@vendor), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Vendor</h1>
</div>

<dl class="dl-horizontal">

  <dt>Name:</dt>
  <dd><%= @vendor.name %></dd>


  <dt>Location:</dt>
  <dd><%= @vendor.location %></dd>


  <dt>Foods list:</dt>
  <dd><%= @vendor.foods_list %></dd>

  <dt>Status:</dt>
  <dd><%= @vendor.status %></dd>


</dl>