config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'schedule/sync'
  end

  devise_for :admins, skip: :registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admins' => 'devise/registrations#update', as: 'admin_registration'
  end

  scope :manage do
    resources :admins
    resources :tellers
    resources :events
    resources :locations
    resources :schedules
    resources :vendors
  end

  root 'admins#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Storytelling Festival</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
      <![endif]-->

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Storytelling Festival", root_path, :class => "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= nav_link 'Admins', admins_path %>
            <%= nav_link 'Tellers', tellers_path %>
            <%= nav_link 'Events', events_path %>
            <%= nav_link 'Locations', locations_path %>
            <%= nav_link 'Schedules', schedules_path %>
            <%= nav_link 'Vendors', vendors_path %>
          </ul>
          <p class="navbar-text pull-right">
          <% if admin_signed_in? %>
            Hello, <%= link_to current_admin.email, edit_admin_registration_path, class: "navbar-link" %>. <%= link_to 'Logout?', destroy_admin_session_path, method: :delete, class: "navbar-link" %> 
          <% else %>
            <%= link_to 'Login', new_admin_session_path, class: "navbar-link" %>
          <% end %>
          </p>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, :class => "alert alert-#{ [:error, :alert, "alert"].include?(name) ? "danger" : "success" } alert-dismissible", :role => "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>